dcConsData = [
	{name:"왈랄.png", keywords:["왈랄", "랄루"], tags:["풀어콘"]},
	{name:"와정말요.png", keywords:["와정말요", "정말요"], tags:["정말", "풀어콘"]},
	{name:"팝콘각.png", keywords:["팝콘각", "팝콘"], tags:["팝콘각", "풀어콘"]},
	{name:"미아내.png", keywords:["미안해", "미아내"], tags:["죄송", "풀어콘"]},
	{name:"고마워.png", keywords:["고마워", "고마어"], tags:["감사", "풀어콘"]},
	{name:"나쁜말.png", keywords:["나쁜말금지", "나쁜말ㄴㄴ"], tags:["화해"]},
	{name:"마오쩌둥.png", keywords:["마오", "마오쩌둥"], tags:["중국"]},
	{name:"검거.png", keywords:["검거", "베이징자택에서검거"], tags:["중국"]},
	{name:"군대.png", keywords:["군대", "군머"], tags:["헬조선"]},
	{name:"입대하살법.gif", keywords:["입대하살법", "입대"], tags:["헬조선"]},
	{name:"저용.png", 	keywords:["저용", "저요"], tags:["저요", "풀어콘"]},
	{name:"ㄷㄷ.png", 	keywords:["ㄷㄷ"], tags:["ㄷㄷ", "풀어콘"]},
	{name:"그럭구나.png", keywords:["그럭구나", "그렇구나"], tags:["풀어콘"]},
	{name:"주작금지.png", keywords:["주작금지", "주작노"], tags:["주작금지", "소녀전선매운맛"]},
	{name:"컨텐츠부족.png", keywords:["컨텐츠부족", "컨텐츠없음"], tags:["컨텐츠부족", "소녀전선매운맛"]},
	{name:"팩트다.png", keywords:["팩트다", "팩트"], tags:["팩트", "소녀전선매운맛"]},
	{name:"망겜.png", keywords:["망겜", "망겜이네"], tags:["망겜", "리오콘"]},
	{name:"기만자.png", keywords:["기만자", "기만자새끼"], tags:["기만", "마루야마"]},
	{name:"지랄하네.png", keywords:["지랄하네", "ㅈㄹ하네"], tags:["욕설", "마루야마"]},
	{name:"잠이나주무십쇼.png",	keywords:["잠이나자라", "잠이나주무십쇼"], tags:["잘자"]},
	{name:"잘자요.png", keywords:["잘자", "잘자요"], tags:["잘자"]},
	{name:"가지마.gif", keywords:["가지마", "어디가"], tags:["가지마", "돼지콘"]},
	{name:"커피한잔.gif", keywords:["커피한잔", "커피타임"], tags:["커피"]},
	{name:"해명해.png", keywords:["해명해", "해명"], tags:["해명해", "풍선콘"]},
	{name:"능지가.png", keywords:["능지가", "님능지가"], tags:["능지처참", "풍선콘"]},
	{name:"야꿀벌.png", keywords:["야꿀벌", "야꿀벌!"], tags:["롤밈"]},
	{name:"개잘핵.png", keywords:["개잘핵", "개잘해"], tags:["개잘핵", "붕괴"]},
	{name:"개못핵.png", keywords:["개못핵", "개못해"], tags:["개못핵", "붕괴"]},
	{name:"운전.gif", keywords:["운전", "유트"], tags:["운전", "붕괴"]},
	{name:"너말이맞아.gif", keywords:["너말이맞아", "니말이맞아"], tags:["붕괴"]},
	{name:"그거똥캐임.png", keywords:["그거똥캐임", "그거별로임"], tags:["붕괴"]},
	{name:"아님말고용.gif", keywords:["아님말고용", "아님말고"], tags:["아님말고", "붕괴"]},
	{name:"귀차나.gif", keywords:["귀차나", "귀찮아"], tags:["귀찮아", "붕괴"]},
	{name:"못참아.gif", keywords:["못참아", "못참는다"], tags:["이건못참지", "붕괴"]},
	{name:"뭐하냐.gif", keywords:["뭐하냐"], tags:["의문", "코노스바"]},
	{name:"경멸.png", keywords:["경멸", "경멸한다"], tags:["경멸", "렘"]},
	{name:"감동.png", keywords:["감동", "감동이야"], tags:["감동", "렘"]},
	{name:"준비완료.png", keywords:["준비완료"], tags:["행동", "렘"]},
	{name:"일하기싫어.png", keywords:["일하기싫어", "일가기싫어"], tags:["싫어", "렘"]},
	{name:"너무좋아.png", keywords:["너무좋아", "좋아요잉"], tags:["좋아", "렘"]},
	{name:"그럼보지마.png", keywords:["그럼보지마", "보지마"], tags:["그럼보지마", "리제로"]},
	{name:"개웃겨.gif", keywords:["개웃겨"], tags:["기쁨", "리제로"]},
	{name:"emt.png", keywords:["E.M.T", "emt", "EMT"], tags:["렘", "기쁨"]},
	{name:"rmt.png", keywords:["R.M.T", "rmt", "RMT"], tags:["기쁨", "리제로"]},
	{name:"잘려고했는데.png", keywords:["잘려고했는데", "잘려고했는데깸"], tags:["잘려고했는데", "리제로"]},
	{name:"내탓ㄴㄴ.png", keywords:["내탓ㄴㄴ", "내탓아님"], tags:["내탓ㄴㄴ", "리제로"]},
	{name:"능지박살.png", keywords:["능지박살", "능박지살"], tags:["능지처참", "프리코네"]},
	{name:"참잘했어요.png", keywords:["참잘했어요", "good"], tags:["잘했어요", "프리코네"]},
	{name:"하지마.gif", keywords:["하지마", "하지말라고"], tags:["분노", "프리코네"]},
	{name:"갑분싸.gif", keywords:["갑분싸"], tags:["분노", "프리코네"]},
	{name:"조아용.gif", keywords:["조아용", "조아여"], tags:["좋아", "프리코네"]},
	{name:"킹리적갓심.gif", keywords:["킹리적갓심"], tags:["의문", "프리코네"]},
	{name:"필살.gif", keywords:["필살", "필살기"], tags:["필살", "프리코네"]},
	{name:"쌉인정.png", keywords:["쌉인정", "ㅆㅇㅈ"], tags:["ㅇㅈ", "프리코네"]},
            {name:"또속.gif", keywords:["또속", "또속음?"], tags:["사기", "프리코네"]},
	{name:"나왔다.gif", keywords:["나왔다", "나왔음"], tags:["하이", "프리코네"]},
	{name:"통장전부.gif", keywords:["통장전부", "꼴아박아"], tags:["과금", "프리코네"]},
	{name:"조용히.gif", keywords:["조용히", "조용히좀"], tags:["분노", "프리코네"]},	
	{name:"오늘운세.png", keywords:["오늘운세", "운세가최악이네"], tags:["오늘운세", "프리코네"]},
	{name:"그건좀.png", keywords:["그건좀", "그건좀.."], tags:["이건아닌듯"]},
	{name:"킹받네.png", keywords:["킹받네", "킹받"], tags:["빡치네"]},
	{name:"나줘.png", keywords:["나줘", "이거나줘"], tags:["나줘", "프암걸"]},
	{name:"구매완료.png", keywords:["구매완료", "구매완"], tags:["구매완료", "프암걸"]},
	{name:"졸리다.gif", keywords:["졸리다", "졸린다"], tags:["피곤", "오덕"]},
	{name:"어억.gif", keywords:["어억"], tags:["놀람", "오덕"]},
	{name:"변신.gif", keywords:["변신"], tags:["행동", "오덕"]},
	{name:"하하.gif", keywords:["하하", "하하하"], tags:["기쁨", "오덕"]},
	{name:"최고.gif", keywords:["최고", "최고다", "최고야"], tags:["기쁨", "오덕"]},
	{name:"노잼.gif", keywords:["노잼", "ㄵ", "ㄴㅈ"], tags:["분노", "오덕"]},
	{name:"핑크빈.gif", keywords:["핑크빈", "두둥"], tags:["행동", "오덕"]},
	{name:"심쿵.gif", keywords:["심쿵"], tags:["행동", "마크로스"]},
	{name:"악몽.gif", keywords:["악몽"], tags:["놀람", "마크로스"]},
	{name:"처묵.gif", keywords:["처묵", "쳐묵"], tags:["행동", "마크로스"]},
	{name:"데헷.png", keywords:["데헷", "데헤헷"], tags:["데헷", "페이몬"]},
	{name:"바위.gif", keywords:["바위", "bye"], tags:["바이", "페이몬"]},
	{name:"헉.gif", keywords:["헉", "허헉"], 	tags:["놀람", "원신"]},
	{name:"아싸.png", keywords:["아싸"], 	tags:["혐오", "원신"]},
	{name:"계산.gif", keywords:["계산", "계산중"], 	tags:["행동", "원신"]},
	{name:"안냥.gif", keywords:["안냥", "안녕"], tags:["하이", "원신"]},
	{name:"할루.gif", keywords:["어서오세요", "헬로"], 	tags:["하이", "원신"]},
	{name:"카즈하1.gif", keywords:["카즈하1", "카즈"], tags:["원신"]},
	{name:"돌아.gif", keywords:["돌아"], 	tags:["행동", "원신"]},
	{name:"폭발.gif", keywords:["폭발", "파괴"], 	tags:["행동", "원신"]},
	{name:"고고.gif", keywords:["고고", "ㄱㄱ"], tags:["고고", "원신"]},
	{name:"머리아프네.gif", keywords:["머리아프네", "ㅈㄴ머리아프네"], tags:["머리아프네", "원신"]},
	{name:"아이고머리야.gif", keywords:["아이고머리야", "아이고두야"], tags:["머리아프네", "원신"]},
	{name:"원신_이왜진.gif", keywords:["이왜진", "진진진"], tags:["이왜진", "원신"]},
	{name:"hi.gif", keywords:["hi", "하이"], tags:["하이", "페이몬"]},
	{name:"클레.gif", keywords:["클레"], tags:["원신"]},
	{name:"클레등장.gif", keywords:["등장"], tags:["원신"]},
	{name:"원신_동공지진.gif", keywords:["동공지진", "크아악"], tags:["동공지진", "원신"]},
	{name:"북끄.gif", 	keywords:["북끄", "부끄럼"], tags:["부끄러움", "원신"]},
            {name:"ㅋㅋㅋ.gif", 	keywords:["ㅋㅋㅋ", "ㅋㅋㅋㅋ"], tags:["ㅋㅋ", "원신"]},
	{name:"쓰읍.gif", 	keywords:["쓰읍", "쓰으읍"], tags:["원신"]},
	{name:"지갑열어.png", keywords:["지갑열어", "과금해"], tags:["원신"]},
	{name:"ㄷㅈ.png", keywords:["ㄷㅈ"], tags:["원신"]},
	{name:"ㄷㅎ.png", keywords:["ㄷㅎ"], tags:["원신"]},
	{name:"한발남았다.gif", keywords:["한발남았다", "남았다"], tags:["원신"]},
	{name:"이거보임.gif", keywords:["이거보임", "이거보임?"], tags:["원신"]},
	{name:"카제.gif", keywords:["카제", "카제다"], tags:["원신"]},
	{name:"다죽어.gif", keywords:["다죽어", "죽어"], tags:["죽어", "원신"]},
	{name:"원바.gif", keywords:["원바", "원바아"], tags:["바이", "원신"]},
	{name:"원하.gif", keywords:["원하", "원하아"], tags:["하이", "원신"]},
	{name:"헬로.gif", keywords:["헬로", "hello"], tags:["하이", "원신"]},
	{name:"다메.gif", keywords:["다메"], tags:["오덕", "원신"]},
	{name:"춤춰.gif", keywords:["춤"], tags:["원신"]},
	{name:"타코야키.gif", keywords:["타코야끼", "타코야키"], tags:["원신"]},
	{name:"찬양해.gif", keywords:["찬양해"], tags:["원신"]},
	{name:"페이몬.gif", keywords:["페이몬"], tags:["귀여워", "원신"]},
	{name:"보이루.gif", keywords:["보이루"], tags:["인사", "원신"]},
	{name:"고맙습니다.png", keywords:["고맙습니다", "고마워요"], tags:["감사", "오덕"]},
	{name:"머선일이고.png", keywords:["머선129", "머선일이고"], tags:["머선일이고", "슬픈고양이"]},
	{name:"ㅜㅜ.gif", keywords:["ㅜㅜ", "울음"], tags:["ㅠㅠ", "슬픈고양이"]},
	{name:"수면.gif", keywords:["수면", "피로"], tags:["피곤", "슬픈고양이"]},
	{name:"ㅠㅠ.gif", keywords:["ㅠㅠ", "울음"], tags:["ㅠㅠ", "슬픈고양이"]},
	{name:"고양이.gif", keywords:["고양이", "야옹이"], tags:["귀여워", "슬픈고양이"]},
	{name:"읭.gif", keywords:["읭", "읭?"], tags:["슬픈고양이"]},
	{name:"절레절레.gif", keywords:["절레절레", "절레"], tags:["슬픈고양이"]},
	{name:"기만.gif", keywords:["기만"], tags:["기만", "슬픈고양이"]},
	{name:"ㅂㅇㄹ.png", keywords:["ㅂㅇㄹ"], tags:["인사", "보겸"]},
	{name:"아디오스.png", keywords:["아디오스"], tags:["인사", "보겸"]},
	{name:"코와이네.png", keywords:["코와이네"], tags:["공포", "보겸"]},
	{name:"내가곶.gif", keywords:["내가곶", "고자라니"], tags:["심영"]},
	{name:"사딸라.gif", keywords:["사딸라", "4딸라"], tags:["심영"]},
	{name:"정신차려.gif", keywords:["4정신차려"], tags:["심영"]},
	{name:"뭐야.gif", keywords:["뭐야", "뭐야?"], tags:["심영"]},
	{name:"안되겠소쏩시다.gif", keywords:["안되겠소쏩시다", "쏩시다"], tags:["심영"]},
	{name:"형님.gif", keywords:["형", "형님"], tags:["심영"]},
	{name:"다시는안하겠소.gif", keywords:["다시는안하겠소", "다씨는안하겠소"], tags:["심영"]},
	{name:"야이빨갱이새끼야.gif", keywords:["야이빨갱이새끼야", "이런빨갱이새끼야"], tags:["심영"]},
	{name:"무야호.gif", keywords:["무야호", "무야아호"], tags:["무야호"]},
	{name:"귀여워.png", keywords:["귀여워", "귀여어"], tags:["귀여워"]},
	{name:"이이잉.gif", keywords:["이이잉", "이잉"], tags:["귀여워"]},
	{name:"화이팅.png", keywords:["화이팅", "화이팅!"], tags:["응원"]},
	{name:"힘내라.gif", keywords:["힘내라", "힘내!"], tags:["응원"]},
	{name:"화해.gif", keywords:["화해", "싸우지마세요"], tags:["화해"]},
	{name:"개추야.gif", keywords:["개추야", "개추다"], tags:["개추", "라오얍콘"]},
	{name:"과몰입.gif", keywords:["과몰입", "과몰입ㄴㄴ"], tags:["과몰입", "라오낙서콘"]},
	{name:"고맙다냥.gif", keywords:["고맙다냥", "다냥"], tags:["감사", "라오얍콘"]},
	{name:"행복해.gif", keywords:["행복해", "햄보캐"], tags:["행복", "라오얍콘"]},
	{name:"재송해요.gif", keywords:["재송해요", "죄송"], tags:["죄송", "라오얍콘"]},
	{name:"뉴비.gif", keywords:["뉴비", "뉴비ㅋㅋ"], tags:["뉴비", "라오얍콘"]},
	{name:"ㅇㅈ이지.gif", keywords:["ㅇㅈ이지", "ㅇㅈ"], tags:["ㅇㅈ", "라오얍콘"]},
	{name:"응애.gif", keywords:["응애", "응애에"], tags:["응애", "모코코콘"]},
	{name:"지나가용.gif", keywords:["지나가용", "지나가여"], tags:["모코코콘"]},
	{name:"이건못참지.png", keywords:["이건못참지", "못참지"], tags:["이건못참지", "모코코콘"]},
	{name:"안녕하살법.gif", keywords:["안녕하살법", "안녕하살"], tags:["안녕하살법", "카구야"]},
	{name:"안녕하살법_받아치기.gif", keywords:["안녕하살법_받아치기", "받아치기"], tags:["카구야"]},
	{name:"야호.gif", keywords:["야호"], tags:["기쁨"]},
	{name:"ㅇㅈ하는부분.gif", keywords:["ㅇㅈ하는부분", "ㅇㅈ한다"], tags:["ㅇㅈ"]},
	{name:"하ㅅㅂ.gif", keywords:["하ㅅㅂ", "하시발"], tags:["ㅅㅂ", "개구리콘"]},
	{name:"살기싫다.gif", keywords:["살기싫다"], tags:["기만", "개구리콘"]},
	{name:"어그로.gif", keywords:["어그로"], tags:["한심", "개구리콘"]},
	{name:"재기해.gif", keywords:["재기해"], tags:["페미니즘"]},
	{name:"싫은데.png", keywords:["싫은데"], tags:["혐오"]},
	{name:"없찐.png", keywords:["없찐"], tags:["혐오"]},
	{name:"혐오.gif", keywords:["혐오", "혐오스런"], tags:["혐오"]},
	{name:"부탁.gif", keywords:["부탁"], tags:["제발"]},
	{name:"야.gif", keywords:["야", "야!"], tags:["분노"]},
	{name:"느낌표.gif", keywords:["느낌표", "!"], tags:["놀람"]},
	{name:"심심.gif", keywords:["심심", "심심해"], tags:["심심"]},
	{name:"ㅗㅜㅑ.png", keywords:["ㅗㅜㅑ"], tags:["19"]},
	{name:"히토미.gif", keywords:["히토미꺼라", "히토미"], tags:["19"]},
	{name:"코코넨네.gif", keywords:["코코넨네", "쿨쿨"], tags:["잘자", "스쿠스타"]},
	{name:"하아병신.gif", keywords:["하아병신", "하아ㅄ"], tags:["병신", "애니마스콘"]},
	{name:"이병신은뭐지.gif", keywords:["이병신은뭐지", "이병신은뭐지?"], tags:["병신", "애니마스콘"]},
	{name:"개소리노.gif", keywords:["개소리노", "개소리"], tags:["개소리", "애니마스콘"]},
	{name:"히익오타쿠.gif", keywords:["히익오타쿠", "힉오타쿠"], tags:["오덕", "애니마스콘"]},
	{name:"구웨에엑.gif", keywords:["구웨에엑", "구웨엑"], tags:["토쏠림"]},
	{name:"ok.gif", keywords:["ok", "오케이"], tags:["OK"]},
	{name:"ㅋ.gif", keywords:["ㅋ"], tags:["ㅋㅋ", "혜리"]},
	{name:"고민.gif", keywords:["고민"], tags:["감정", "혜리"]},
	{name:"긴장.gif", keywords:["긴장"], tags:["감정", "혜리"]},
	{name:"뭐임.gif", keywords:["뭐임"], tags:["기쁨", "혜리"]},
	{name:"존잘.gif", keywords:["존잘", "존잘러"], tags:["감탄", "혜리"]},
	{name:"출발.gif", keywords:["출발"], tags:["ㄱㄱ", "혜리"]},
	{name:"풉.gif", keywords:["풉", "푸웁"], tags:["비웃음", "혜리"]},
	{name:"이건맞지.gif", keywords:["이건맞지", "이건ㅇㅈ"], tags:["ㅇㅈ", "아이즈원"]},
	{name:"감사합니다.gif", keywords:["감사합니다", "아리가또"], tags:["감사", "아이즈원"]},
	{name:"존맛.gif", keywords:["존맛"], tags:["음식움짤"]},
	{name:"닭가슴살.png", keywords:["닭가슴살"], tags:["음식움짤"]},
	{name:"닭다리살.png", keywords:["닭다리살"], tags:["음식움짤"]},
	{name:"에어프라이어.png", keywords:["에어프라이어"], tags:["음식움짤"]},
	{name:"참치.png", keywords:["참치"], tags:["음식움짤"]},
	{name:"연어.png", keywords:["연어"], tags:["음식움짤"]},
	{name:"밥.gif", keywords:["밥"], tags:["음식움짤"]},
	{name:"민초.gif", keywords:["민초", "미각"], tags:["음식움짤", "민트초코"]},
	{name:"민하.gif", keywords:["민하", "민hi"], tags:["음식움짤", "민트초코"]},
	{name:"닥쳐.gif", keywords:["닥치세요", "닥치셈"], tags:["분노", "아이즈원"]},
	{name:"안사요.gif", keywords:["안사요", "안사"], tags:["음식움짤", "민트초코"]},
	{name:"ㅆㅅㅌㅊ.gif", keywords:["ㅆㅅㅌㅊ", "ㅅㅌㅊ"], tags:["ㅆㅅㅌㅊ", "아이즈원"]},
	{name:"ㅆㅎㅌㅊ.gif", keywords:["ㅆㅎㅌㅊ"], tags:["ㅆㅎㅌㅊ", "아이즈원"]},
	{name:"ㅎㅌㅊ.gif", keywords:["ㅎㅌㅊ"], tags:["ㅎㅌㅊ", "아이즈원"]},
	{name:"ㄴㅇㄱ.gif", keywords:["ㄴㅇㄱ"], tags:["행동", "아이즈원"]},
	{name:"어케했누.gif", keywords:["어케했누", "어케했노"], tags:["어케했누", "아이즈원"]},
	{name:"쇼크사.gif", keywords:["쇼크사", "쑈크사"], tags:["아이즈원"]},
	{name:"따아봉.gif", keywords:["굿굿", "굿굿굿!"], tags:["응원", "아이즈원"]},
	{name:"충성.gif", keywords:["충성", "충성!"], tags:["충성", "아이즈원"]},
	{name:"인사박습니다.gif", keywords:["인사박습니다", "인사오지게박습니다"], tags:["인사", "아이즈원"]},
	{name:"뭐함.gif", keywords:["뭐함", "뭐함?"], tags:["뭐함", "아이즈원"]},
	{name:"잘했어요.gif", keywords:["잘했어요", "잘했어"], tags:["잘했어요", "아이즈원"]},
	{name:"맞으실.gif", keywords:["맞으실", "맞으실?"], tags:["아이즈원"]},
	{name:"클라스.gif", keywords:["클라스", "클라쓰"], tags:["아이즈원"]},
	{name:"맛점.gif", keywords:["맛점"], tags:["행동", "차은우"]},
	{name:"맛저.gif", keywords:["맛저"], tags:["행동", "차은우"]},
	{name:"족발.gif", keywords:["족발"], tags:["음식움짤"]},
	{name:"떡볶이.gif", keywords:["떡볶이", "떡보끼"], tags:["음식움짤"]},
	{name:"짜장면.gif", keywords:["짜장면", "자장면"], tags:["음식움짤"]},
	{name:"구워.gif", keywords:["구워"], tags:["음식움짤"]},
	{name:"치킨.gif", keywords:["치킨", "닭고기"], tags:["음식움짤"]},
	{name:"치느님.gif", keywords:["치느님", "닭다리"], tags:["음식움짤"]},
	{name:"탕수육.gif", keywords:["탕수육", "부먹충"], tags:["음식움짤"]},
	{name:"부대찌개.gif", keywords:["부대찌개", "부머찌개"], tags:["음식움짤"]},
	{name:"민초욕하지마.gif", keywords:["민초욕하지마", "민초맛있음"], tags:["민트초코", "음식움짤"]},
	{name:"민초하세요.gif", keywords:["민초하세요", "민초해"], tags:["음식움짤"]},
	{name:"민초쌈.gif", keywords:["민초쌈", "민초를쌈에싸서"], tags:["음식움짤"]},
	{name:"라면.gif", keywords:["라면", "라면짤"], tags:["음식움짤"]},
	{name:"먹방1.gif", keywords:["먹방1", "하정우먹방1"], tags:["음식움짤"]},
	{name:"돈까스.gif", keywords:["돈까스", "돈가스"], tags:["음식움짤"]},
	{name:"국밥충.gif", keywords:["국밥충", "국밥"], tags:["음식움짤"]},
	{name:"케이크.gif", keywords:["케이크", "케잌"], tags:["음식움짤"]},
	{name:"스테이크.gif", keywords:["스테이크"], tags:["음식움짤"]},
	{name:"돼지국밥.gif", keywords:["돼지국밥"], tags:["음식움짤"]},
	{name:"냉면.gif", keywords:["냉면"], tags:["음식움짤"]},
	{name:"콜라.gif", keywords:["콜라"], tags:["음식움짤"]},
	{name:"짬뽕.gif", keywords:["짬뽕"], tags:["음식움짤"]},
	{name:"파전.gif", keywords:["파전"], tags:["음식움짤"]},
	{name:"삼겹살.gif", keywords:["삼겹살"], tags:["음식움짤"]},
	{name:"돈가스정식.png", keywords:["돈가스정식", "돈까스정식"], tags:["음식움짤"]},
	{name:"피자.gif", keywords:["피자", "휫자"], tags:["음식움짤"]},
	{name:"극혐.gif", keywords:["극혐", "그켬"], tags:["극혐", "아이오아이"]},
	{name:"폭파.gif", keywords:["폭파", "폭퐈"], tags:["폭파", "프리코네"]},
	{name:"승인.gif", keywords:["승인", "도장콱"], tags:["승인", "럽샤인"]},
	{name:"박수.gif", keywords:["박수", "짝짝짝"], tags:["박수", "럽샤인"]},
	{name:"ㅋㅋ.gif", keywords:["ㅋㅋ", "ㅋ"], tags:["일론머스크"]},
	{name:"날아간다.gif", keywords:["날아간다", "날라간다"], tags:["일론머스크"]},
	{name:"극호감.png", keywords:["극호감", "호감"], tags:["호감"]},
	{name:"ㄹㅇㅋㅋ.gif", keywords:["ㄹㅇㅋㅋ", "레알ㅋㅋ"], tags:["ㄹㅇㅋㅋ"]},
	{name:"ㅂㄷㅂㄷ.gif", keywords:["부들부들", "ㅂㄷㅂㄷ"], tags:["분노"]},
	{name:"나대지마.gif", keywords:["나대지마", "나대지마라"], tags:["나대지마"]},
	{name:"여기요.gif", keywords:["여기"], tags:["청춘돼지", "덕후"]},
	{name:"아해봐.gif", keywords:["아해봐"], tags:["덕후"]},
	{name:"화남.gif", keywords:["화났어", "화났어?"], tags:["청춘돼지", "덕후"]},
	{name:"끄덕.gif", keywords:["끄덕"], tags:["청춘돼지", "덕후"]},
	{name:"돼지다.gif", keywords:["돼지새끼"], tags:["청춘돼지", "덕후"]},
	{name:"사랑해.gif", keywords:["사랑해"], tags:["청춘돼지", "사랑"]},
	{name:"나가.gif", keywords:["나가"], tags:["청춘돼지", "덕후"]},
	{name:"진짜.gif", keywords:["진짜"], tags:["청춘돼지", "덕후"]},
	{name:"우욱씹.gif", keywords:["우욱", "우욱씹"], tags:["덕후"]},
	{name:"옴뇸뇸.gif", keywords:["옴뇸뇸", "옴뇸"], tags:["쿠쿠룬콘"]},
	{name:"오또케오또케.gif", keywords:["오또케오또케", "오또케"], tags:["오또케오또케", "쿠쿠룬콘"]},
	{name:"메롱.gif", keywords:["메롱", "메에롱"], tags:["메롱"]},
	{name:"정답.png", keywords:["정답", "딩동댕"], tags:["정답", "니노콘"]},
	{name:"오답.png", keywords:["오답", "땡"], tags:["오답", "니노콘"]},
	{name:"좋은아침.gif", keywords:["좋은아침", "goodmorning"], tags:["인사", "아이유"]},
	{name:"ㅅㄱ.gif", keywords:["ㅅㄱ", "수고"], tags:["수고", "아이유"]},
	{name:"땡큐.gif", keywords:["땡큐", "thankyou"], tags:["감사", "아이유"]},
	{name:"안물안궁.gif", keywords:["안물안궁", "안물"], tags:["안물", "아이유"]},
	{name:"아냐.gif", keywords:["아냐", "아님"], tags:["행동", "아이유"]},
	{name:"ㅇㅇ.gif", keywords:["ㅇㅇ"], tags:["행동", "아이유"]},
	{name:"그래서.gif", keywords:["그래서"], tags:["행동", "아이유"]},
	{name:"딱대.gif", keywords:["딱대", "딱대라"], tags:["딱대", "아이유"]},
	{name:"지켜본다.gif", keywords:["지켜본다", "지켜봄"], tags:["지켜본다", "아이유"]},
	{name:"어엉.gif", keywords:["어엉", "어엉?"], tags:["놀람", "아이유"]},
	{name:"아.gif", keywords:["아", "아~"], tags:["놀람", "아이유"]},
	{name:"오우.gif", keywords:["오우"], tags:["놀람", "아이유"]},
	{name:"때리실려구.gif", keywords:["때리실려구"], tags:["분노", "아이유"]},
	{name:"뭐라했냐.gif", keywords:["뭐라했냐"], tags:["아이유"]},
	{name:"아니이맛은.gif", keywords:["아니이맛은", "이맛은"], tags:["맛있다", "아이유"]},
	{name:"개빡치네.gif", keywords:["개빡치네", "빡치네"], tags:["분노", "아이유"]},
	{name:"끝났다.gif", keywords:["끝났다", "끝남"], tags:["끝났다", "아이유"]},
	{name:"두둥등장.gif", keywords:["두둥등장", "ㄷㄷㄷㅈ"], tags:["하이", "아이유"]},
	{name:"어휴.gif", keywords:["어휴"], tags:["한심", "아이유"]},
	{name:"시끄러.gif", keywords:["시끄러"], tags:["분노", "아이유"]},
	{name:"ㅉ.gif", keywords:["ㅉ", "ㅉㅉ"], tags:["한심", "아이유"]},
	{name:"말잇못.png", keywords:["말잇못", "잇못"], tags:["황당", "아이유"]},
	{name:"한심.gif", keywords:["한심", "한심해"], tags:["한심", "아이유"]},
	{name:"어서오세요.gif", keywords:["어서와", "난하"], tags:["인사", "아이유"]},
	{name:"들어가세요.gif", keywords:["들어가세요", "ㅃㅇ"], tags:["인사", "아이유"]},
	{name:"선넘네.gif", keywords:["선넘네"], tags:["분노", "아이유"]},
	{name:"손모가지걸어라.gif", keywords:["손모가지", "손모가지걸어라"], tags:["분노", "아이유"]},
	{name:"끄아악.gif", keywords:["끄아악", "꾸아악"], tags:["끄아악", "구구단"]},
	{name:"와우.gif", keywords:["와우", "와우!"], tags:["놀람", "구구단"]},
	{name:"제발.gif", keywords:["제발", "제발요"], tags:["제발", "구구단"]},
	{name:"빠져든다.gif", keywords:["빠져든다", "빠져들어"], tags:["구구단"]},
	{name:"외출.gif", keywords:["외출", "외출한다"], tags:["행동", "유리나"]},
	{name:"찾아간다.gif", keywords:["찾아간다", "현실갱"], tags:["행동", "유리나"]},
	{name:"니가문제야.gif", keywords:["니가문제야"], tags:["행동", "유리나"]},
	{name:"대박.gif", keywords:["대박", "레게노"], tags:["행동", "유리나"]},
	{name:"뭐해.gif", keywords:["뭐해", "하아"], tags:["행동", "유리나"]},
	{name:"인성.gif", keywords:["인성", "인성문제"], tags:["행동", "유리나"]},
	{name:"존예.gif", keywords:["존예"], tags:["행동", "유리나"]},
	{name:"파이팅.gif", keywords:["파이팅"], tags:["응원", "유리나"]},
	{name:"창피.gif", keywords:["창피"], tags:["부끄러움", "유리나"]},
	{name:"반가워.gif", keywords:["반가워"], tags:["인사", "유리나"]},
	{name:"ㅂㅇ.gif", keywords:["ㅂㅇ", "빠이"], tags:["인사", "노기자카"]},
	{name:"몰라.gif", keywords:["몰라", "몰라요"], tags:["의문", "노기자카"]},
	{name:"데힛.gif", keywords:["힛"], tags:["의문", "노기자카"]},
	{name:"ㄴㄴ.gif", keywords:["ㄴㄴ", "노노"], tags:["거절", "노기자카"]},
	{name:"총맞아.gif", keywords:["총맞아"], tags:["행동", "노기자카"]},
	{name:"ㄹㅇ.gif", keywords:["ㄹㅇ", "ㄹㅇ?"], tags:["의문", "노기자카"]},
	{name:"ㅎㄷㄷ.gif", keywords:["ㅎㄷ", "ㅎㄷㄷ"], tags:["놀람", "노기자카"]},
	{name:"왜사냐.gif", keywords:["왜사냐"], tags:["의문", "AKB"]},
	{name:"^^7.gif", keywords:["^^7"], tags:["행동", "AKB"]},
	{name:"들뜸.gif", keywords:["들뜸"], tags:["기쁨", "AKB"]},
	{name:"허걱스.gif", keywords:["놀람"], tags:["놀람", "AKB"]},
	{name:"뭐먹지.gif", keywords:["뭐먹지"], tags:["의문", "AKB"]},
	{name:"힐끔.gif", keywords:["힐끔"], tags:["행동", "니지프"]},
	{name:"천재.gif", keywords:["천재", "천잰데", "똑똑해"], tags:["행동", "니지프"]},
	{name:"시선회피.gif", keywords:["시선회피"], tags:["행동", "니지프"]},
	{name:"나는누구.gif", keywords:["나는누구"], tags:["놀람", "니지프"]},
	{name:"헐.gif", keywords:["헐"], tags:["놀람", "니지프"]},
	{name:"ㅊㅊ.gif", keywords:["ㅊㅊ", "ㅊㅋ", "ㅊㅋㅊㅋ", "축하해"], tags:["기쁨", "SKE"]},
	{name:"실화.gif", keywords:["실화", "실화냐", "실화임?", "실화냐?"], tags:["행동", "SKE"]},
	{name:"들어가.gif", keywords:["들어가", "들어가요", "잘가셈"], tags:["인사", "SKE"]},
	{name:"티타임.gif", keywords:["티타임"], tags:["행동", "SKE"]},
	{name:"머리쓰자.gif", keywords:["머리쓰자"], tags:["행동", "SKE"]},
	{name:"인간아.gif", keywords:["으휴", "인간아"], tags:["행동", "SKE"]},
	{name:"밥먹자.gif", keywords:["배고파", "밥먹자"], tags:["행동", "SKE"]},
	{name:"행복회로.gif", keywords:["행복회로"], tags:["행동", "SKE"]},
	{name:"커피좀.gif", keywords:["커피좀", "커피"], tags:["행동", "SKE"]},
	{name:"좋아해.gif", keywords:["좋아해", "러브"], tags:["행동", "SKE"]},
	{name:"공부.gif", keywords:["공부", "공부해라"], tags:["행동", "SKE"]},
	{name:"피곤.png", keywords:["피곤", "피곤해"], tags:["피곤"]},
	{name:"또오세요.gif", keywords:["또오세요"], tags:["바이", "블랙핑크"]},
	{name:"멈춰.gif", keywords:["멈춰", "폭력멈춰"], tags:["사회밈"]},
	{name:"저리가.gif", keywords:["저리가", "꺼져"], tags:["머니게임"]},
	{name:"나락.gif", keywords:["나락", "NARAK"], tags:["머니게임"]},
	{name:"엄.png", keywords:["엄", "UM"], tags:["엄준식"]},
	{name:"엄준식화이팅.png", keywords:["엄준식화이팅", "엄준식 화이팅"], tags:["엄준식"]},
	{name:"ㅇㄱㄹㅇ.gif", keywords:["ㅇㄱㄹㅇ", "이게레알"], tags:["ㄹㅇㅋㅋ", "댕댕콘"]},
	{name:"빤스런.png", keywords:["빤스런", "런런"], tags:["빤스런"]},
	{name:"푸쉬업.gif", keywords:["푸쉬업", "팔굽혀펴기"], tags:["행동", "아이카츠"]},
	{name:"켁.gif", keywords:["켁"], tags:["행동", "아이카츠"]},
	{name:"에어기타.gif", keywords:["에어기타"], tags:["행동", "아이카츠"]},
	{name:"비명.gif", keywords:["비명", "꺄아"], tags:["행동", "오덕"]},
	{name:"예스.gif", keywords:["예스", "yes"], tags:["행동", "오덕"]},
	{name:"호구.png", keywords:["호구"], tags:["행동", "오덕"]},
	{name:"월요일.png", keywords:["월요일"], tags:["행동", "오덕"]},
	{name:"친구.png", keywords:["친구"], tags:["행동", "오덕"]},
	{name:"금손.png", keywords:["금손"], tags:["행동", "오덕"]},
	{name:"세탁.png", keywords:["세탁"], tags:["행동", "뱅드림"]},
	{name:"작작.gif", keywords:["작작", "작작해"], tags:["행동", "뱅드림"]},
	{name:"1절.gif", keywords:["1절", "1절만"], tags:["행동", "오덕"]},
	{name:"시무룩.gif", keywords:["시무룩"], tags:["행동", "오덕"]},
	{name:"뭐라는거야.png", keywords:["뭐라는거야", "뭐라는거임"], tags:["행동", "오덕"]},
	{name:"떡상.png", keywords:["떡상", "떡상각"], tags:["행동", "오덕"]},
	{name:"파오후.png", keywords:["파오후"], tags:["혐오", "오덕"]},
	{name:"묻히고싶어요.gif", keywords:["묻히고싶어", "묻히고싶어요"], tags:["혐오", "오덕"]},
	{name:"뭘봐.png", keywords:["뭘봐"], tags:["혐오", "오덕"]},
	{name:"방역.gif", keywords:["방역"], tags:["혐오", "오덕"]},
	{name:"경고1.png", keywords:["경고1"], tags:["혐오", "오덕"]},
	{name:"경고2.png", keywords:["경고2"], tags:["혐오", "오덕"]},
	{name:"경고3.png", keywords:["경고3"], tags:["혐오", "오덕"]},
	{name:"마무리.gif", keywords:["마무리"], tags:["행동", "오덕"]},
	{name:"노사람.png", keywords:["노사람"], tags:["혐오", "오덕"]},
	{name:"틀딱이다.gif", keywords:["틀딱이다"], tags:["혐오", "오덕"]},
	{name:"다메나노요.gif", keywords:["다메나노요", "다메다메"], tags:["오덕"]},
	{name:"달려.gif", keywords:["달려"], tags:["행동", "오덕"]},
	{name:"반가워요.gif", keywords:["반갑습니다"], tags:["오덕"]},
	{name:"교통사고.gif", keywords:["교통사고"], tags:["오덕"]},
	{name:"사고.gif", keywords:["사고"], tags:["오덕"]},
	{name:"허걱.gif", keywords:["허걱"], tags:["오덕"]},
	{name:"얍.gif", keywords:["얍", "얍얍"], tags:["행동", "오덕"]},
	{name:"아닌데.png", keywords:["아닌데"], tags:["오덕"]},
	{name:"수박.png", keywords:["수박"], tags:["오덕"]},
	{name:"덥다.png", keywords:["덥다", "더워"], tags:["오덕"]},
	{name:"축제.png", keywords:["축제"], tags:["오덕"]},
	{name:"매미.png", keywords:["매미"], tags:["오덕"]},
	{name:"모기.png", keywords:["모기"], tags:["오덕"]},
	{name:"뿅뿅.png", keywords:["뿅", "뿅뿅"], tags:["오덕"]},
	{name:"안녕히주무셨어요.png", keywords:["안녕히주무셨어요"], tags:["인사", "오덕"]},
	{name:"맞는데.png", keywords:["맞는데"], tags:["오덕"]},
	{name:"플렉스.png", keywords:["플렉스", "flex"], tags:["오덕"]},
	{name:"미친놈아.gif", keywords:["미친놈아"], tags:["오덕"]},
	{name:"히사시부리.png", keywords:["히사시부리"], tags:["오덕"]},
	{name:"라면먹고가.gif", keywords:["라면먹고갈래", "라면먹고갈래?"], tags:["행동", "유루캠"]},
	{name:"안전운전.gif", keywords:["안전운전", "안전운전해"], tags:["행동", "유루캠"]},
	{name:"잘먹겠습니다.gif", keywords:["잘먹겠습니다"], tags:["행동", "유루캠"]},
	{name:"오늘뭐먹지.gif", keywords:["오늘뭐먹지"], tags:["행동", "유루캠"]},
	{name:"날씨좋다.gif", keywords:["날씨좋다"], tags:["행동", "유루캠"]},
	{name:"차한잔.gif", keywords:["차한잔", "차"], tags:["행동", "유루캠"]},
	{name:"사줘.gif", keywords:["사줘", "사주세요"], tags:["행동", "유루유리"]},
	{name:"갖고싶어.gif", keywords:["갖고싶어"], tags:["행동", "유루유리"]},
	{name:"힘들다.gif", keywords:["힘들다", "힘들어"], tags:["행동", "오덕"]},
	{name:"드럼.gif", keywords:["드럼"], tags:["행동", "오덕"]},
            {name:"확마.gif", keywords:["확마", "확마그냥"], tags:["이명박"]},
            {name:"배고파요.gif", keywords:["헝그리", "배고픔"], tags:["이명박"]},
            {name:"여러분이거다.gif", keywords:["여러분", "여러분이거다", "여러분 이거다"], tags:["이명박"]},
            {name:"기침.gif", keywords:["기침", "콜록"], tags:["이명박"]},
            {name:"하트.gif", keywords:["하트", "하트표"], tags:["이명박"]},
	{name:"큐트이니.gif", keywords:["큐트이니", "이니"], tags:["문재인"]},
	{name:"오우야.png", keywords:["오우야", "ㅗㅜㅑ"], tags:["문재인"]},
	{name:"호우.gif", keywords:["호우", "호와우"], tags:["문재인"]},
	{name:"중국몽.png", keywords:["중국몽"], tags:["문재인"]},
	{name:"잘생겼이니.png", keywords:["잘생겼이니", "잘생겼으니"], tags:["문재인"]},
	{name:"걸스두낫.png", keywords:["걸스두낫", "프린스"], tags:["페미니즘"]},
	{name:"이건좀아닌듯.gif", keywords:["이건좀아닌듯", "이건좀"], tags:["이건아닌듯", "문재인"]},
	{name:"부끄러움.gif", keywords:["부끄러움", "부끄럽"], tags:["부끄러움", "문재인"]},
	{name:"박수짝짝.gif", keywords:["박수짝짝", "짝짝짝"], tags:["박근혜"]},
	{name:"흑우.png", keywords:["흑우", "흑우어서오고"], tags:["흑우", "둘리"]},
	{name:"군머.png", keywords:["군머", "하군대"], tags:["멘붕"]},
            {name:"이건아닌듯.gif", keywords:["이건아닌듯", "이건아니야"], tags:["이건아닌듯", "김정은"]},
	{name:"흐뭇.gif", keywords:["흐뭇", "흐뭇해"], tags:["박수", "김정은"]},
	{name:"아ㅅㅂ.gif", keywords:["아ㅅㅂ", "아놔"], tags:["아ㅅㅂ", "자연인"]},
	{name:"야나두.png", keywords:["야나두", "야나두?"], tags:["야나두"]},
	{name:"야너두.png", keywords:["야너두", "야너두?"], tags:["야나두"]}, 
	{name:"그게뭔데.gif", keywords:["그게뭔데", "그게뭔데십덕아"], tags:["오덕", "STU"]}, 
	{name:"하나도모르겠네.gif", keywords:["하나도모르겠네", "모르겠네"], tags:["의문", "STU"]}, 
	{name:"라고말합니다.png", keywords:["라고말합니다", "라고말함"], tags:["오덕"]}, 
	{name:"자지마.png", keywords:["자지마", "자면나빠"], tags:["오덕"]},
	{name:"짝.png", keywords:["짝", "싸대기"], tags:["오덕"]},
	{name:"정답이뭐냐.png", keywords:["정답이뭐냐"], tags:["오덕"]}, 
	{name:"트로피카나.gif", keywords:["트로피카나", "스파클링"], tags:["트로피카나"]}, 
	{name:"이게아닌데.gif", keywords:["이게아닌데", "이거아닌데"], tags:["이게아닌데", "강호동"]}, 
	{name:"인정못함.gif", keywords:["인정못함", "노ㅇㅈ"], tags:["노ㅇㅈ", "강호동"]}, 
	{name:"닭은푹삶아야.gif", keywords:["닭은푹삶아야", "닭푹삶"], tags:["강호동"]}, 
	{name:"나만아니면돼.gif", keywords:["나만아니면돼", "나만아니면"], tags:["나만아니면돼", "강호동"]}, 
	{name:"해봤어요.gif", keywords:["해봤어", "해봤어요"], tags:["해봤어", "강호동"]}, 
	{name:"아ㅅㅂ.gif", keywords:["아ㅅㅂ", "진짜ㅅㅂ"], tags:["아ㅅㅂ", "자연인"]}, 
	{name:"ㅋㅋㅋㅋㅋ.gif", keywords:["ㅋㅋㅋㅋㅋ", "ㅋㅋㅋㅋㅋㅋ"], tags:["ㅋㅋ"]}, 
	{name:"미안하다이거보여줄려고.gif", keywords:["미안하다이거보여줄려고", "어그로끌었다"], tags:["이거보여줄려고", "한국밈"]}, 
	{name:"비틱.png", keywords:["비틱", "네덕"], tags:["비틱"]}, 
	{name:"너굴맨등장.png", keywords:["너굴맨"], tags:["너굴맨"]}, 
	{name:"너굴맨.png", keywords:["너굴맨이왔으니", "걱정하지말라구"], tags:["너굴맨"]}, 
	{name:"엄마콘.png", keywords:["엄마콘", "밖에좀나가라"], tags:["밖에좀나가라"]}, 
	{name:"골때리네.gif", keywords:["골때리네", "와이거"], tags:["외국밈"]}, 
	{name:"딴데가서놀아라.gif", keywords:["딴데가서놀아라", "딴데가라"], tags:["외국밈"]}, 
            {name:"같이보자.gif", keywords:["같이보자", "우리같이보자"], tags:["레인보우"]},
	{name:"황당.gif", keywords:["황당", "황당하네"], tags:["황당", "레인보우"]},
            {name:"그게끝이에요.gif", keywords:["그게끝이에요", "그게끝이에요?"], tags:["황당", "레인보우"]},
            {name:"빙고.gif", keywords:["빙고", "BINGO"], tags:["정답", "레인보우"]},
	{name:"아저씨누구에요.gif", keywords:["아저씨누구에요", "아저씨누구?"], tags:["누구세요", "레인보우"]},
	{name:"아이씐나.gif", keywords:["아이씐나"], tags:["레인보우"]},
            {name:"애쓴다.gif", keywords:["애쓴다"], tags:["한심", "레인보우"]},
	{name:"뭐래.gif", keywords:["뭐래"], tags:["레인보우"]},
	{name:"사기.png", keywords:["그사기는", "뭐야그사기는"], tags:["사기"]},
	{name:"뭐라고.png", keywords:["뭐라고", "뭐라고?"], tags:["놀람"]},
	{name:"목소리.png", keywords:["목소리", "목소리뭐야"], tags:["놀람"]},
	{name:"쉬면안돼요.gif", keywords:["쉬면안돼요", "쉬지마셈"], tags:["쉬면안돼요"]},
	{name:"근근웹.gif", keywords:["근근웹으로", "루리웹으로"], tags:["디펜스콘"]},
	{name:"일베로.gif", keywords:["일베로", "일베로꺼져"], tags:["디펜스콘"]},
	{name:"일베로.png", keywords:["일베꺼져"], tags:["디펜스콘"]},
	{name:"훈수금지.png", keywords:["훈수금지", "훈수충ㄴㄴ"], tags:["훈수금지", "디펜스콘"]},
	{name:"국추.gif", keywords:["국추", "국추드림"], tags:["이국주"]},
	{name:"바이.gif", keywords:["바이", "빠이"], tags:["바이", "케이온"]},
	{name:"행보캐.gif", keywords:["행보캐", "행복"], tags:["행복", "케이온"]},
	{name:"가지마세요.gif", keywords:["가지마세요", "가지마셈"], tags:["행동", "케이온"]},
	{name:"비눗방울.gif", keywords:["비눗방울", "비누방울"], tags:["행복", "케이온"]},
	{name:"찰칵.gif", keywords:["찰칵", "사진"], tags:["행동", "케이온"]},
	{name:"푸훕.gif", keywords:["푸훕"], tags:["비웃음", "케이온"]},
	{name:"호고곡.gif", keywords:["호고곡"], tags:["놀람", "케이온"]},
	{name:"노답.gif", keywords:["노답", "ㄴㄷ"], tags:["노답", "케이온"]},
	{name:"띠용.gif", keywords:["띠용", "띠요옹"], tags:["놀람", "케이온"]},
	{name:"글쎄.gif", keywords:["글쎄", "글쎄요"], tags:["글쎄", "케이온"]},
	{name:"헤헤.gif", keywords:["헤헤", "헤헤헤"], tags:["ㅋㅋ", "케이온"]},
	{name:"너요너.png", keywords:["너요너", "너요"], tags:["오덕", "케이온"]},
	{name:"볼콕.gif", keywords:["볼콕", "볼찌르기"], tags:["볼콕", "슈타게"]},
	{name:"앙기모띠.png", keywords:["앙기모띠", "앙기모링"], tags:["앙기모띠", "메구밍"]},
	{name:"기분나빠.png", keywords:["기분나빠", "기분나쁘네"], tags:["기분나쁨", "메구밍"]},
	{name:"와슈발.png", keywords:["와슈발", "와슈바"], tags:["아ㅅㅂ", "메구밍"]},
	{name:"니손이문제.png", keywords:["니손이문제", "니손문제"], tags:["니손이문제", "메구밍"]},
	{name:"어휴십덕새기.png", keywords:["어휴십덕새기", "십뜨억아"], tags:["오덕", "밀리시타"]},
	{name:"생각이없니.png", keywords:["생각이없니", "생각이없니?"], tags:["능지처참", "밀리시타"]},
	{name:"손절할게.png", keywords:["손절할게", "손절함"], tags:["손절할게", "밀리시타"]},
	{name:"그건니가.gif", keywords:["그건니가", "그건니가못해서"], tags:["개못핵", "밀리시타"]},
	{name:"수고요.gif", keywords:["수고요", "수고하셨음"], tags:["수고", "밀리시타"]},
	{name:"싫은데요.gif", keywords:["싫은데요", "싫은데여"], tags:["싫어", "밀리시타"]},
	{name:"너그런거보니.gif", keywords:["너그런거보니", "그런거보니"], tags:["너그런거보니", "밀리시타"]},
	{name:"너그런거하니.gif", keywords:["너그런거하니", "그런거하니"], tags:["너그런거하니", "밀리시타"]},
	{name:"찐.gif", keywords:["찐", "찐-따"], tags:["찐", "밀리시타"]},
	{name:"브라보.gif", keywords:["브라보", "cool"], tags:["잘했어요", "송중기"]},
	{name:"조심해.gif", keywords:["조심해", "조심해라"], tags:["송중기"]},
	{name:"싫다.png", keywords:["싫다"], tags:["혐오", "브레이브걸스"]},
	{name:"따봉.gif", keywords:["따봉", "따봉!"], tags:["응원", "브레이브걸스"]},
	{name:"제정신.gif", keywords:["제정신"], tags:["한심", "브레이브걸스"]},
	{name:"쌍따봉.gif", keywords:["쌍따봉", "쌍따봉!"], tags:["응원", "브레이브걸스"]},
	{name:"잘해따.gif", keywords:["잘해따", "잘해따!"], tags:["잘했어요", "AKB48"]},
	{name:"백종원거짓말.gif", keywords:["거짓말하지말고", "거짓말"], tags:["분노", "백종원"]},
	{name:"아진짜.gif", keywords:["아진짜", "아나진짜"], tags:["분노", "백종원"]},
	{name:"백종원맛있어.gif", keywords:["맛있어요", "맛있네요"], tags:["맛있다", "백종원"]},
	{name:"이거좀심한데.gif", keywords:["이거좀심한데", "이거심한데"], tags:["이건아닌듯", "백종원"]},
	{name:"백종원극대노.gif", keywords:["극대노", "개빡침!"], tags:["분노", "백종원"]},
	{name:"맘에들어.gif", keywords:["이거지", "맘에들어"], tags:["잘했어요", "백종원"]},
	{name:"우마이.gif", keywords:["우마이", "우마이데스네"], tags:["맛있다"]},
	{name:"근근.png", keywords:["근근", "근근웹"], tags:["혐오"]},
	{name:"오유.png", keywords:["오유", "오늘의유머"], tags:["혐오"]},
	{name:"일베.png", keywords:["일베저장소", "일베충"], tags:["혐오"]},
	{name:"유해사이트.png", keywords:["유해사이트"], tags:["19", "혐오"]},
	{name:"틀딱.gif", keywords:["틀딱", "틀"], tags:["혐오"]},
	{name:"이시국.gif", keywords:["이시국", "이시국에"], tags:["혐오"]},
	{name:"개.gif", keywords:["개"], tags:["분노"]},
	{name:"찬양.png", keywords:["찬양"], tags:["놀람"]},
	{name:"람쥐썬더.gif", keywords:["람쥐썬더"], tags:["한국밈"]},
	{name:"살아있네.png", keywords:["살아있네"], tags:["한국밈"]},
	{name:"내가너.gif", keywords:["내가너좋아하면안되냐", "장경철", "내가너"], tags:["한국밈"]},
	{name:"내가너.png", keywords:["안되냐"], tags:["한국밈"]},
	{name:"뒤져.gif", keywords:["뒤지세요"], tags:["한국밈"]},
	{name:"느그서장.gif", keywords:["느그서장"], tags:["한국밈"]},
	{name:"이건사야돼.png", keywords:["이건사야돼"], tags:["과금", "오덕"]},
	{name:"한남.png", keywords:["한남"], tags:["페미니즘", "오덕"]},
	{name:"코르셋.png", keywords:["코르셋"], tags:["페미니즘", "오덕"]},
	{name:"남혐콘.png", keywords:["한국남자"], tags:["페미니즘", "혐오"]},
	{name:"펄럭.gif", keywords:["펄럭"], tags:["국뽕"]},
	{name:"국뽕.png", keywords:["국뽕"], tags:["국뽕"]},
	{name:"한국.png", keywords:["한국"], tags:["국뽕"]},
	{name:"머랭.gif", keywords:["머랭"], tags:["귀여워"]},
	{name:"에베베.gif", keywords:["에베베"], tags:["비웃음"]},
	{name:"누나.gif", keywords:["누나"], tags:["비웃음"]},
	{name:"틀니.png", keywords:["틀딱아니에요", "틀니"], tags:["분노"]},
	{name:"ㅇㅈ.gif", keywords:["ㅇㅈ"], tags:["ㅇㅈ", "배리나"]},
	{name:"계세요.gif", keywords:["계세요"], tags:["인사", "배리나"]},
	{name:"키보드.gif", keywords:["키보드"], tags:["행동"]},
	{name:"돌겠네.gif", keywords:["돌겠네"], tags:["행동"]},
	{name:"외웠어요.gif", keywords:["외웠어요"], tags:["행동"]},
	{name:"고래밥.png", keywords:["고래밥"], tags:["과자"]},
	{name:"고소미.png", keywords:["고소미"], tags:["과자"]},
	{name:"다이제.png", keywords:["다이제"], tags:["과자"]},
	{name:"맛동산.png", keywords:["맛동산"], tags:["과자"]},
	{name:"빅파이.png", keywords:["빅파이"], tags:["과자"]},
	{name:"새우깡.png", keywords:["새우깡"], tags:["과자"]},
	{name:"뿌셔뿌셔.png", keywords:["뿌셔뿌셔"], tags:["과자"]},
	{name:"바나나킥.png", keywords:["바나나킥"], tags:["과자"]},
	{name:"양파링.png", keywords:["양파링"], tags:["과자"]},
	{name:"마가렛트.png", keywords:["마가렛트", "마가레트"], tags:["과자"]},
	{name:"오감자.png", keywords:["오감자"], tags:["과자"]},
	{name:"빼빼로.png", keywords:["빼빼로"], tags:["과자"]},
	{name:"오예스.png", keywords:["오예스"], tags:["과자"]},
	{name:"초코파이.png", keywords:["초코파이"], tags:["과자"]},
	{name:"오레오.png", keywords:["오레오"], tags:["과자"]},
	{name:"자갈치.png", keywords:["자갈치"], tags:["과자"]},
	{name:"칸쵸.png", keywords:["칸쵸"], tags:["과자"]},
	{name:"포카칩.png", keywords:["포카칩"], tags:["과자"]},
	{name:"쿠크다스.png", keywords:["쿠크다스"], tags:["과자"]},
	{name:"홈런볼.png", keywords:["홈런볼"], tags:["과자"]},
	{name:"허니버터칩.png", keywords:["허니버터칩", "허니버터"], tags:["과자"]},
	{name:"나쵸.png", keywords:["나쵸"], tags:["과자"]},
	{name:"꼬깔콘.png", keywords:["꼬깔콘"], tags:["과자"]},
	{name:"칙촉.png", keywords:["칙촉"], tags:["과자"]},
	{name:"콘칩.png", keywords:["콘칩"], tags:["과자"]},
	{name:"초코하임.png", keywords:["초코하임"], tags:["과자"]},
	{name:"치토스.png", keywords:["치토스"], tags:["과자"]},
	{name:"카스타드.png", keywords:["카스타드"], tags:["과자"]},
	{name:"포스틱.png", keywords:["포스틱"], tags:["과자"]},
	{name:"프링글스.png", keywords:["프링글스"], tags:["과자"]},
	{name:"제크.png", keywords:["제크"], tags:["과자"]},
	{name:"초코.png", keywords:["초코"], tags:["극혐"]},
	{name:"민트초코.gif", keywords:["민트초코"], tags:["극혐"]},
	{name:"싸움.gif", keywords:["싸움", "개싸움"], tags:["극혐"]},
	{name:"K-스트리머.png", keywords:["K스트리머"], tags:["극혐"]}
];